# Generated by Django 4.0.5 on 2022-06-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('life_sphere', models.CharField(max_length=30)),
                ('user_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('life_sphere', models.CharField(max_length=30)),
                ('prompt_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Romantic', 'Romantic Partner'), ('Friend', 'Friendship'), ('Roommate', 'Roommates'), ('Other', 'Something Else')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('pronouns', models.CharField(choices=[('She', 'She/Her/Hers'), ('They', 'They/Them/Theirs'), ('He', 'He/Him/His'), (models.CharField(max_length=30), "I don't use gender pronouns.")], max_length=30)),
            ],
        ),
    ]
